name: vost
description: Aplicação para VOST

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_page_indicator: ^0.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2

  #testing
  test: ^1.5.1+1
  mockito: ^4.0.0

  #built_value
  built_collection: ^4.1.0
  built_value: ^6.3.0

  #core
  rxdart: ^0.22.4
  shared_preferences: ^0.4.3
  stream_disposable: ^0.0.1

  # Network
  dio: 2.1.0
  http: ^0.12.0

  #localizations
  intl: ^0.15.8
  intl_translation: ^0.17.7

  # UI
  flare_flutter: ^1.6.2

  #Navigation
  url_launcher: ^5.1.4

dev_dependencies:
  build_runner: ^1.2.3
  built_value_generator: ^6.3.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/flare/vost_logo.flr
    - assets/images/
